language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
env:
  - DJANGO=2.0
  - DJANGO=2.1
  - DJANGO=2.2
install:
# command to install dependencies
  - "pip install coveralls"
  - pip install pep8
  - pip install -q Django==$DJANGO
  - "pip install ."
before_script:
  - pep8 --ignore=E501,E225,E123 django_spaghetti 
  - cd docs ; sphinx-build -nW -b html -d _build/doctrees . _build/html ; cd ..

# command to run tests
script:
  - coverage run --branch --source=django_spaghetti manage.py test
matrix:
  exclude:
    - python: "3.4"
      env: DJANGO=2.1
after_success:
  - coveralls
