language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
env:
  - DJANGO=1.8
  - DJANGO=1.9
install:
# command to install dependencies
  - "pip install coveralls"
  - pip install -q Django==$DJANGO --use-mirrors
  - "pip install ."
# command to run tests
script:
  - coverage run --branch --source=django_spaghetti manage.py test
matrix:
  exclude:
    - python: "2.6"
      env: DJANGO=1.7
    - python: "2.6"
      env: DJANGO=1.8
after_success:
  - coveralls
