language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
env:
  - DJANGO=1.8
  - DJANGO=1.9
  - DJANGO=1.10
install:
# command to install dependencies
  - "pip install coveralls"
  - pip install pep8
  - pip install -q Django==$DJANGO
  - "pip install ."
before_script:
  - pep8 --ignore=E501,E225,E123 django_spaghetti 
  - cd docs ; sphinx-build -nW -b html -d _build/doctrees . _build/html ; cd ..
# command to run tests
script:
  - coverage run --branch --source=django_spaghetti manage.py test
matrix:
  exclude:
    - python: "2.6"
      env: DJANGO=1.8
after_success:
  - coveralls
