name: Testing
on: [push, pull_request]

jobs:
  python_lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v1
      - name: Setup Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install flake8
        run: pip install flake8
      - name: Lint
        run: flake8

  test:
    needs:
      - python_lint
    name: Testing
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install tox
        run: pip install tox

      - name: Run tests
        run: tox
